### ISSUE TITLE
Board resolutions data definitions not loading to metadata table

### ISSUE THREAD

**Issue by jasonlally** [DataSF/metadata-mgmt-tool#10]
Board resolutions definitions are attached, but nothing is loading to the master data dictionary.

Inventory ID is MTA-0088

@j9recurses - can you look into this?

**Comment by j9recurses** [comment]
@jasonlally this is fixed now. There was a bug in one of the config files. Basically, there is a sub job that loads the asset fields and data dictionary data (that is in a csv file) info into socrata. 

In short: the path in the config file was set to the older fetch-metadata-fields directory, instead of the current metadata-management-tool. This meant that the subjob was reading old data in the fetch-metadata-fields dir instead of the most current data in the metadata-management-tool dir. 

As result, new data dictionaries and datasets weren't getting loaded properly. I reran it and the drones data is there. Also there were 4 new data dictionary attachments- the definitions in those have been loaded, so hopefully this fix resolves the issue.
